name: flutter_storybook_example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^12.1.1
  flutter_storybook:
    path: ..
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  mews_pedantic: ^0.20.0

dependency_overrides:
  device_frame:
    git:
      url: https://github.com/bradrushworth/flutter_device_preview.git
      path: device_frame
  device_preview:
    git:
      url: https://github.com/bradrushworth/flutter_device_preview.git
      path: device_preview

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/code_snippets/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf