name: flutter_storybook
description: A storybook for Flutter widgets. Live preview of isolated widgets for faster development and showcase.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  any_syntax_highlighter: ^0.0.13
  collection: ^1.17.2
  flutter:
    sdk: flutter
  go_router: ^12.1.3
  nested: ^1.0.0
  pointer_interceptor: ^0.9.3+7
  provider: ">=6.0.0 <7.0.0"
  recase: ^4.1.0
  adaptive_test:
    git: https://github.com/FlutterPackages/adaptive_test.git
  device_frame:
    git:
      url: https://github.com/FlutterPackages/flutter_device_preview.git
      path: device_frame

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.9.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
