name: storybook_toolkit
description: A storybook for Flutter widgets. Live preview of isolated widgets for faster development and showcase.
repository: https://github.com/mjablecnik/storybook_toolkit
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  any_syntax_highlighter: ^0.0.13
  collection: ^1.17.2
  go_router: ^12.1.3
  nested: ^1.0.0
  pointer_interceptor: ^0.9.3+7
  provider: ">=6.0.0 <7.0.0"
  recase: ^4.1.0
  vader_popup: ^0.1.1
  adaptive_golden_test: ^0.5.1
  device_frame_plus: ^1.2.1
  meta: ^1.12.0

dev_dependencies:
  golden_toolkit: ^0.9.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
