name: storybook_toolkit
description: A storybook for Flutter widgets. Live preview of isolated widgets for faster development and showcase.
issue_tracker: https://github.com/StorybookToolkit/storybook_toolkit/issues
repository: https://github.com/StorybookToolkit/storybook_toolkit
version: 1.3.0

topics:
  - storybook
  - widgetbook
  - widgets
  - toolkit

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  any_syntax_highlighter: ^0.0.13
  go_router: ^14.2.2
  inspector: ^2.1.0
  pointer_interceptor: ^0.10.1+1
  provider: ">=6.0.0 <7.0.0"
  vader_popup: ^0.1.2
  device_frame_plus: ^1.2.1

dev_dependencies:
  golden_toolkit: ^0.9.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
